services:
  gomokulivegame:
    image: gomokulivegameapp:latest
    build: .
    ports:
      - "18080:18080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.8'           
          memory: 300m          
        reservations:
          cpus: '0.2'           
          memory: 100m          
